version: '3.5'
services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    command: npm run dev      
    image: opengram
    container_name: opengram
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
    - $APPLICATION_PORT:$APPLICATION_PORT
    volumes:
    - .:/home/node/app
    - node_modules:/home/node/app/node_modules
    networks:
    - opengram-network

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "27017:27017"
    volumes:     
      - ./data:/data/db
    networks:
      - opengram-network  

networks:
  opengram-network:
    name: custom_opengram
    driver: bridge
volumes:
  node_modules:  